### ISSUE TITLE
对象字符串含某些字符时会发生转换异常

### ISSUE THREAD

**Issue by nickeaglenny** [qwe7989199/RubyTools#1]
1.包含`「`或`」`时，整体转换会失效，包括\k标签也会消失：
转化元:
`{\k28}「さ{\k24}よ{\k31}な{\k49}ら」{\k24}だ{\k29}け{\k55}だっ{\k24}た`
转换结果：
`「さよなら」だけだった`

2.包含片假名时，整体转换会失效，包括\k标签也会消失：
转化元:
`{\k47}フェ{\k13}ン{\k39}ス{\k11}越{\k43}し{\k46}に{\k56}重{\k40}なっ{\k37}てい{\k38}た`
转换结果：
`フェンス越しに重なっていた`

3.包含促音`っ`时，连带促音前的字符以及之后所有字符会转换消失：
转化元:
`{\k40}そ{\k26}の{\k51}一{\k58}言{\k14}で{\k37}す{\k26}べ{\k26}て{\k29}が{\k21}分{\k55}かっ{\k43}た`
转换结果：
`{\k40}そ{\k26}の{\k109}一言|<ひとこと{\k14}で{\k37}す{\k26}べ{\k26}て{\k29}が{\k21}分|<わ`

4.包含全角或半角空格，`、`时，符号后续所有字符都会转换消失：
转化元:
`{\k25}分{\k27}か{\k25}り{\k25}合{\k28}え{\k10}る{\k33}さ{\k78}　信{\k33}じ{\k28}て{\k16}る{\k246}よ`
转换结果：
`{\k25}分|<わ{\k27}か{\k25}り{\k25}合|<あ{\k28}え{\k10}る{\k33}さ`

转化元:
`{\k60}二{\k31}人{\k42}今{\k58}、夜{\k20}に{\k22}駆{\k28}け{\k25}出{\k40}し{\k20}て{\k9}い{\k105}く`
转换结果：
`{\k60}二|<ふた{\k31}人|<り{\k42}今|<いま`

以上情况是否能改善？还是只能人工手动介入？
谢谢！

**Comment by qwe7989199** [comment]
![screen](https://user-images.githubusercontent.com/10990771/89747426-afd67200-daf9-11ea-85ea-d0c078b09c71.png)
已修复，将txt改ass，可以得到测试文件

[ruby_test.txt](https://github.com/qwe7989199/RubyTools/files/5048786/ruby_test.txt)
