### ISSUE TITLE
V1終了

### ISSUE THREAD

**Issue by Needfire-Gl** [qwe7989199/RubyTools#2]
V1終了予定時期につきましては2022年1月末を予定しております。
新バージョン（V2）に関しては[こちら](https://developer.yahoo.co.jp/webapi/jlp/furigana/v2/furigana.html)をご覧ください。

**Comment by qwe7989199** [comment]
V2アップデート完了 (https://github.com/qwe7989199/RubyTools/commit/85d00616f880ecf45b29cdc7f4a6f675dd002658)
