### ISSUE TITLE
为什么运行完成后，有的汉字没有生成音标？而且速度非常慢，要联网获取假名发音？能不能改成用mecab之类直接本地获取发音？微信nlanguage

### ISSUE THREAD

**Issue by nissansz** [qwe7989199/RubyTools#4]
![image](https://user-images.githubusercontent.com/41010669/192095959-14123466-c59f-4393-8a94-0189af94771d.png)

**Comment by qwe7989199** [comment]
“お前”注音的相关信息丢失修复[c4ca0c1](https://github.com/qwe7989199/RubyTools/commit/c4ca0c13069e97195809d1b4ad1c48df11ccf0d1)

mecab相关：
技术上可以改用本地处理，有人写过了，不在本项目的讨论范围内
