### ISSUE TITLE
卡拉OK字幕生成音标后的显示不对，变成这种了，是要怎么操作？怎么解决？{\k44}今|<いま{\k0} {\k95}心|<こころ{\k34}か

### ISSUE THREAD

**Issue by nissansz** [qwe7989199/RubyTools#5]
卡拉OK字幕生成音标后的显示不对，变成这种了，是要怎么操作？怎么解决？{\k44}今|<いま{\k0} {\k95}心|<こころ{\k34}か
![image](https://user-images.githubusercontent.com/41010669/192102967-ec1b66ce-5fb2-40af-8e11-63b31f32095e.png)

**Comment by qwe7989199** [comment]
已经打K的假名标注生成结果是按照Aegisub的注音假名格式
https://aegi.vmoe.info/docs/3.2/Furigana_karaoke/
是预期内的行为
