### ISSUE TITLE
生成的字幕坐标有误

### ISSUE THREAD

**Issue by arroe99** [qwe7989199/RubyTools#7]
如图，字幕的position在0,-30，在视频画面外面了。是什么问题？可以解决吗？
![image](https://github.com/qwe7989199/RubyTools/assets/113248688/777a89c1-eae9-4bdd-aaef-4b5f64f56bbc)

![image](https://github.com/qwe7989199/RubyTools/assets/113248688/ae2a50dc-4dc8-4617-bd0a-5872c013adb8)

**Comment by arroe99** [comment]
图中的字幕文本是：近付いてくる光りに\N别让渐渐接近的光阴

是因为有换行符的原因吗？

**Comment by qwe7989199** [comment]
首先不支持中日文\N分行的直接标注
其次检查一下脚本的分辨率有没有问题

**Comment by arroe99** [comment]
感谢解答。我现在的处理是先用单行日语字幕生成平假名标注，然后在换行加入中文翻译。稍微麻烦点，但问题解决了。
